### PR TITLE
get latest client information from database

### PR DESCRIPTION
**Pull request by Jamiras**
Verified versions in DB match current API results:
image

```
$ curl "https://retroachievements.org/dorequest.php?r=latestclient&e=1"
{"Success":true,"MinimumVersion":"0.060","LatestVersion":"1.0","LatestVersionUrl":"http:\/\/retroachievements.org\/bin\/RAP64.zip","LatestVersionUrlX64":null}
$ curl "https://retroachievements.org/dorequest.php?r=latestclient&e=2"
{"Success":true,"MinimumVersion":"1.1","LatestVersion":"1.1","LatestVersionUrl":"http:\/\/retroachievements.org\/bin\/RASnes9x.zip","LatestVersionUrlX64":"http:\/\/retroachievements.org\/bin\/RASnes9x-x64.zip"}
$ curl "https://retroachievements.org/dorequest.php?r=latestclient&e=3"
{"Success":true,"MinimumVersion":"1.0.1","LatestVersion":"1.1.0","LatestVersionUrl":"http:\/\/retroachievements.org\/bin\/RAVBA.zip","LatestVersionUrlX64":"http:\/\/retroachievements.org\/bin\/RAVBA-x64.zip"}
$ curl "https://retroachievements.org/dorequest.php?r=latestclient&e=5"
{"Success":true,"MinimumVersion":"1.1","LatestVersion":"1.1","LatestVersionUrl":"http:\/\/retroachievements.org\/bin\/RANes.zip","LatestVersionUrlX64":"http:\/\/retroachievements.org\/bin\/RANes-x64.zip"}
$ curl "https://retroachievements.org/dorequest.php?r=latestclient&e=7"
{"Success":true,"MinimumVersion":"1.4.0","LatestVersion":"1.8.0","LatestVersionUrl":"http:\/\/retroachievements.org\/bin\/RALibretro.zip","LatestVersionUrlX64":"http:\/\/retroachievements.org\/bin\/RALibretro-x64.zip"}
$ curl "https://retroachievements.org/dorequest.php?r=latestclient&e=8"
{"Success":true,"MinimumVersion":"1.0","LatestVersion":"1.0","LatestVersionUrl":"http:\/\/retroachievements.org\/bin\/RAMeka.zip","LatestVersionUrlX64":null}
$ curl "https://retroachievements.org/dorequest.php?r=latestclient&e=9"
{"Success":true,"MinimumVersion":"1.1.3","LatestVersion":"1.2.0","LatestVersionUrl":"http:\/\/retroachievements.org\/bin\/RAQUASI88.zip","LatestVersionUrlX64":null}
$ curl "https://retroachievements.org/dorequest.php?r=latestclient&e=10"
{"Success":true,"MinimumVersion":"1.1.1","LatestVersion":"1.3.0","LatestVersionUrl":"http:\/\/retroachievements.org\/bin\/RAppleWin.zip","LatestVersionUrlX64":null}
```

Note that querying 4 and 6 currently returns items with Minimum/LatestVersion of 0, and this will return Unknown Client instead. Additionally, querying values above 10 may return data associated to external emulators that previously wasn't accessible. Since this is an internal API, I'm not worried about these changes.

### CODE REVIEW

**Review by wescopeland — APPROVED** [review]
Verified locally.

The only thing I'm noticing that may be worth asking about is the call to `latestclient` seems to be kicking off 7 SQL queries. I'm not sure how frequently this gets called. If it's frequent, given the relative static nature of the data, I'm wondering if it may be worth caching in Redis?

**Comment by Jamiras** [comment]
It would be called once each time the user starts up an RAx emulator.

What are the 7 queries? I was slightly concerned that `emulator->latestRelease` might not be caching the result. It could be getting called up to three times.

**Comment by wescopeland** [comment]
Here's the PHP code I'm running to get some debug output:
```php
$emulator = Emulator::find(1);

$format_url = function (?string $url): ?string {
  return !$url || str_starts_with($url, "http")
    ? $url
    : config("app.url") . "/" . $url;
};
$response["MinimumVersion"] =
  $emulator->minimumSupportedRelease?->version ??
  $emulator->latestRelease->version;
$response["LatestVersion"] = $emulator->latestRelease->version;
$response["LatestVersionUrl"] = $format_url($emulator->download_url);
$response["LatestVersionUrlX64"] = $format_url($emulator->download_x64_url);

dump($response);
```

Here's the list of queries I see:
```
SELECT
  *
FROM
  `emulators`
WHERE
  `emulators`.`id` = 1
  AND `emulators`.`deleted_at` IS NULL
LIMIT
  1

SELECT
  *
FROM
  `emulator_releases`
WHERE
  `emulator_releases`.`emulator_id` = 1
  AND `emulator_releases`.`emulator_id` IS NOT NULL
  AND `minimum` = 1
  AND `emulator_releases`.`deleted_at` IS NULL
ORDER BY
  `created_at` DESC
LIMIT
  1

SELECT
  *
FROM
  `emulators`
WHERE
  `emulators`.`id` IN (1)
  AND `emulators`.`deleted_at` IS NULL

SELECT
  *
FROM
  `media`
WHERE
  `media`.`model_id` IN (44)
  AND `media`.`model_type` = 'emulator.release'

SELECT
  *
FROM
  `emulator_releases`
WHERE
  `emulator_releases`.`emulator_id` = 1
  AND `emulator_releases`.`emulator_id` IS NOT NULL
  AND `stable` = 1
  AND `emulator_releases`.`deleted_at` IS NULL
ORDER BY
  `created_at` DESC
LIMIT
  1

SELECT
  *
FROM
  `emulators`
WHERE
  `emulators`.`id` IN (1)
  AND `emulators`.`deleted_at` IS NULL

SELECT
  *
FROM
  `media`
WHERE
  `media`.`model_id` IN (117)
  AND `media`.`model_type` = 'emulator.release'
```

Screenshot 2024-10-12 at 1 59 10 PM

**Comment by wescopeland** [comment]
I also tried to do something like `Emulator::with(["latestRelease.media", "minimumSupportedRelease"])->find(1)` but that didn't seem to reduce the query count.

**Comment by Jamiras** [comment]
Looks like four of those queries are for populating data on the EmulatorRelease that's not needed. I suspect because of this: https://github.com/RetroAchievements/RAWeb/blob/e7455d4ae16b89291b814ba2334b216c8a1ab4e1/app/Models/EmulatorRelease.php#L37-L40

**Comment by wescopeland** [comment]
Confirmed, commenting out that block reduces the query count to 3:

```
SELECT
  *
FROM
  `emulators`
WHERE
  `emulators`.`id` = 1
  AND `emulators`.`deleted_at` IS NULL
LIMIT
  1

SELECT
  *
FROM
  `emulator_releases`
WHERE
  `emulator_releases`.`emulator_id` = 1
  AND `emulator_releases`.`emulator_id` IS NOT NULL
  AND `minimum` = 1
  AND `emulator_releases`.`deleted_at` IS NULL
ORDER BY
  `created_at` DESC
LIMIT
  1

SELECT
  *
FROM
  `emulator_releases`
WHERE
  `emulator_releases`.`emulator_id` = 1
  AND `emulator_releases`.`emulator_id` IS NOT NULL
  AND `stable` = 1
  AND `emulator_releases`.`deleted_at` IS NULL
ORDER BY
  `created_at` DESC
LIMIT
  1
```

**Comment by Jamiras** [comment]
I've removed the forced `with` fields. Doesn't seem to affect the management pages, and nothing else is using EmulatorRelease.

**Review by wescopeland — APPROVED** [review]

**Pull request merged**
