### PR TITLE
parse MemAddr with RegEx and show a fancy table

### PR DESCRIPTION
**Pull request by meleu**
**First of all**: huge thanks to @stt for showing me that it's possible to parse MemAddr with Regular Expressions :nerd_face:

This PR changes the behavior of `GetAchievementPatchReadableHTML()`, making it produce this output:
parsememaddr

rather than the current buggy one:
oldparsememaddr

### CODE REVIEW

**Comment by meleu** [comment]
@luchaos marked you as a reviewer because my PHP code looks a bit ugly :sweat_smile:

**Comment by GameDragon2k** [comment]
Damn that looks nice. Way to go!

**Comment by meleu** [comment]
in this last commit I've used `<small>` for the CodeNotes. IMO it looks less messy:

smallorbigcodenotes

**Comment by GameDragon2k** [comment]
Your image is a little small @meleu but `<small>` looks better from what I can tell.

**Comment by meleu** [comment]
IIRC luchaos said that he would be busy this weekend, and since this PR is not changing anything on database stuff (it's just a presentation thing), I'm going to merge it and putting it alive.

We can polish the code later on v2. ;)

**Pull request merged**
