### PR TITLE
Update viewforum.php

### PR DESCRIPTION
**Pull request by Ben-Ghazi**
Change Developer Notice to reflect permission change.

### CODE REVIEW

**Comment by meleu** [comment]
@Ben-Ghazi 
changes unrelated to the viewforum.php should come in a different Pull Request.

**Comment by Ben-Ghazi** [comment]
Yeah I thought I was creating a different pull request but it got added to this one for some reason, are people only allowed 1 pull request at a time or did I just do it wrong?

**Comment by meleu** [comment]
there's no limit for the number of Pull Requests. The problem here is that you edited a file on the branch you used to submit this Pull Request.

When you submit a PR you want to merge a branch into another one. In this specific case here, you want to merge `Ben-Ghazi:develop` (the `develop` branch from your RAWeb fork) into `RetroAchievements:develop`.

So if you continue editing files in the `develop` branch of your fork, the change is propagated to this PR.

**Comment by meleu** [comment]
implemented your original idea via 04f75b3e147cd879c47e1eea1613a001ff8c47b9
closing this PR.

**Pull request closed without merging**
