### PR TITLE
Use thunderer/shortcode for shortcode processing

### LINKED ISSUE #384: Forum: Code doesn't ignore forum formatting or style tags
When using a code block in the forums, I would think it should be styled as plain text, and not be able to use the tags within them. I just noticed when testing after backslashes weren't weren't being displayed ~while using monospace ascii art~ inside code.

In the following image, the first spoiler tag probably shouldn't be displayed as an actual spoiler tag, but as the regular text because it is inside a code block:

code-backslash

Example of how code blocks should probably work:
`code-backslash`

### PR DESCRIPTION
**Pull request by luchaos**
Omit invalid and incorrectly nested tags.
Do not render tags within code tags.
Supports various formats e.g.:
```
[url="example.com"]
[url]example.com[/url]
[url="example.com"]Example[/url]
```

Closes #636
Fixes #384

### CODE REVIEW

**Comment by Jamiras** [comment]
I get the following error trying to view a forum:
```
Fatal error: Uncaught Error: Class 'Thunder\Shortcode\HandlerContainer\HandlerContainer' not found in /home/brian/source/RAWeb/src/Shortcode/Shortcode.php:32 Stack trace: #0 /home/brian/source/RAWeb/src/Shortcode/Shortcode.php(18): RA\Shortcode\Shortcode->parse('What's &lsquo;I...', Array) #1 /home/brian/source/RAWeb/public/viewtopic.php(305): RA\Shortcode\Shortcode::render('What's &lsquo;I...') #2 {main} thrown in /home/brian/source/RAWeb/src/Shortcode/Shortcode.php on line 32
```

I see similar errors trying to view comments on an achievement, but not for games or users.

I don't see any error on the "send private message page", but the formatting buttons are not clickable. The error appears after hitting Send, and when trying to view the message as the recipient.

**Comment by luchaos** [comment]
> ```
> Fatal error: Uncaught Error: Class 'Thunder\Shortcode\HandlerContainer\HandlerContainer' not found in /home/brian/source/RAWeb/src/Shortcode/Shortcode.php:32
> Stack trace: 
> #0 /home/brian/source/RAWeb/src/Shortcode/Shortcode.php(18): RA\Shortcode\Shortcode->parse('What's &lsquo;I...', Array) 
> #1 /home/brian/source/RAWeb/public/viewtopic.php(305): RA\Shortcode\Shortcode::render('What's &lsquo;I...') 
> #2 {main} thrown in /home/brian/source/RAWeb/src/Shortcode/Shortcode.php on line 32
> ```

`Class not found` sounds like the dependency was not installed.
Can you please run `composer install` and try again?

**Comment by Jamiras** [comment]
That fixed the forum display issue, private messaging, and format buttons not working.

Ran into this on the achievement page:
```
Fatal error: Uncaught TypeError: Argument 1 passed to RA\Shortcode\Shortcode::render() must be of the type string, null given, called in /home/brian/source/RAWeb/public/achievementInfo.php on line 258 and defined in /home/brian/source/RAWeb/src/Shortcode/Shortcode.php:16
Stack trace: 
#0 /home/brian/source/RAWeb/public/achievementInfo.php(258): RA\Shortcode\Shortcode::render(NULL, Array)
#1 {main} thrown in /home/brian/source/RAWeb/src/Shortcode/Shortcode.php on line 16
```
Looks like `$embedVidURL` can be NULL.

**Comment by luchaos** [comment]
> Looks like `$embedVidURL` can be NULL.

Missed that detail, thanks!

**Review by Jamiras — APPROVED** [review]

**Pull request merged**
