### PR TITLE
renamed "Neo Geo" to "Neo Geo Pocket" - closes #77

### LINKED ISSUE #77: rename "Neo Geo" to "Neo Geo Pocket" to avoid confusion
Some users are asking me about the possibility to get cheevos for the classic Neo Geo fighting games, Metal Slug, etc. They didn't realized that the "new" system is Neo Geo **Pocket** [Color].

### PR DESCRIPTION
**Pull request by meleu**
Is merging here enough to change on the site? :thinking: 

Well, waiting a more experienced guy check this... ;)

### CODE REVIEW

**Comment by ScottFromDerby** [comment]
Hmm. Not done this before. I'll keep pressing buttons until something works

**Comment by ScottFromDerby** [comment]
Oooh yea sorry, I changed it in the db, forgot there was another one in the menu

**Comment by ScottFromDerby** [comment]
Oooooooo I think I did it! Now to pull on the server

**Comment by GameDragon2k** [comment]
Yep, it's good. =)

**Comment by ScottFromDerby** [comment]
I *think* I did it. Let me know if it went ok please

**Comment by GameDragon2k** [comment]
Looks good to me, not seeing any issues on the site either.

**Comment by meleu** [comment]
thanks guys! :+1:

**Pull request merged**
