### PR TITLE
feat(achievement): add type indicators to tooltip cards

### PR DESCRIPTION
**Pull request by wescopeland**
This PR adds type indicators to achievement tooltip cards and makes subtle style adjustments to the card content.

Changes:
* "HARDCORE" is no longer shown. Instead, similar to the dev feed, the card now subtly implies that hardcore is our default mode and tacks on a "(softcore)" indicator if the achievement was unlocked in softcore mode.
* Unlocked is now using `.smalldate`.
* Type indicators are using a new thin type indicator component. The tooltips are statically rendered, and we want to minimize how much DOM we're stuffing into them. The type indicator component used on game pages is dense.

**Before**
Screenshot 2023-12-13 at 6 26 06 PM

**After**
Screenshot 2023-12-13 at 6 27 05 PM

### CODE REVIEW

**Comment by wescopeland** [comment]
Temporarily moving to draft. This needs to be updated to accommodate for the new user setting introduced in https://github.com/RetroAchievements/RAWeb/pull/2084.

**Review by Jamiras — COMMENTED** [review]
I seem to have lost all hardcore indicators in the recent games list:
image

it still shows the yellow border on the game and achievement pages
image


vs. softcore:
image

**Comment by wescopeland** [comment]
Good catch, resolved in latest.

**Review by Jamiras — APPROVED** [review]

**Comment by Alexdatadestroyer** [comment]
This was already approved and merged, but I will give a comment here even if it's ends up being ignored... This would also justify the negative thumb on OP.

Softcore Mode was always standardized on RetroAchievements as achievement winning. I would prefer the name "HARDCORE" to continue being mentioned instead of just mentioning about their unlock date. The text "(softcore)" being shown at end of unlock String is not something I find appropriated either. It's REALLY needed to suppress the "HARDCORE" text, then, it's better to show the unlocked achievement with the classic yellow border that we are used to see and without yellow border for Softcore cases so. The Card Tooltip must have something discernible to show more clearly what achievement was unlocked in Hardcore and what was in Softcore. The unlock text is too slow to be used for that.

**Comment by Alexdatadestroyer** [comment]
Also, this is another Pull Request that features the unnecessary change regarding the default datetime used on RA Website. It's an International community, not a US one. This kind of thing is being common since when RAWeb V5.0 came to light arbitrarily. It was mentioned better here on #2115

**Comment by wescopeland** [comment]
> The text "(softcore)" being shown at end of unlock String is not something I find appropriated either. It's REALLY needed to suppress the "HARDCORE" text

This wasn't an arbitrary choice. Emulators are moving towards hardcore mode being the default instead of softcore mode.

> This kind of thing is being common since when RAWeb V5.0 came to light arbitrarily.

RAWeb V5.0 did not come to light "arbitrarily". V5.0 was not released at random or without a clear reason. The team did a lot of work to improve site performance with the V5.X releases.

**Comment by Alexdatadestroyer** [comment]
> > This kind of thing is being common since when RAWeb V5.0 came to light arbitrarily.
> 
> RAWeb V5.0 did not come to light "arbitrarily". V5.0 was not released at random or without a clear reason. The team did a lot of work to improve site performance with the V5.X releases.

This is a typo on that sentence. Sorry. The correct sentence was supposed to be "This kind of thing is being common since when **RAWeb V5.0 came to light which was implemented arbitrarily**". The intention wasn't to say that RAWeb V5.0+ is useless, but to say that Datetime Format changes from 24-hour DM to 12-hour MD were put without any valid reason since then...

**Pull request merged**
