### PR TITLE
fix: handle PlayerAchievementLocked events in DispatchUpdateDeveloperContributionYieldJob

### PR DESCRIPTION
**Pull request by wescopeland**
Reverts the changes from https://github.com/RetroAchievements/RAWeb/pull/2545 and implements a fix for the root cause of the issue.

`DispatchUpdateDeveloperContributionYieldJob` is not handling the `PlayerAchievementLocked` case. This results in the contrib yield job being called with a null user.

### CODE REVIEW

**Comment by Jamiras** [comment]
> `DispatchUpdateDeveloperContributionYieldJob` is not handling the `PlayerAchievementLocked` case. This results in the contrib yield job being called with a null user.

It seems like this code is/was trying to handle the null user, but there might be a order of operations issue in the logic:
```
        if (!$user instanceof User) {
            return;
        }
```

**Comment by wescopeland** [comment]
Figured it out.

`findOrFail()` explodes if it's querying for a soft-deleted user. Checking for `PlayerAchievementLocked` turns out to not be necessary - I don't believe this is currently being dispatched anywhere.

Should be addressed in latest.

**Review by Jamiras — APPROVED** [review]
Did you have any insight onto whether `(!$user instanceof User)` is logically correct? Does it need to be `(!($user instanceof User))`?

**Comment by wescopeland** [comment]
It's logically correct as-is. [`instanceof` has a higher operator precedence than logical not](https://www.php.net/manual/en/language.operators.precedence.php).

**Pull request merged**
