### PR TITLE
API_GetAchievementUnlocks also returns 'MemAddr'

### PR DESCRIPTION
**Pull request by meleu**
It'll allow me to easily make the RABot's `!mem` command show the logic of an actual achievement on discord (https://github.com/RetroAchievements/RABot/issues/27).

IMO it'll be extremely useful for jrdevs and code reviewers.

### CODE REVIEW

**Comment by Keltron3030** [comment]
If you could somehow also display the relevant code notes it would be amazing.  I know it's a tall order.

**Comment by meleu** [comment]
Agreed, but, as Code Notes are in another DB table, that would require more tweaking.

I'll let it as a "point for improvement".

**Comment by luchaos** [comment]
Would it be possible to use the dorequest patch method for getting the trigger (memAddr) instead? As the bot has access to that according to its environment variables.
I obfuscated exposed memory triggers in other web api responses in the past to make sure the integration api is the only one to expose them fully. https://github.com/RetroAchievements/RAWeb/blob/develop/public/API/API_GetGameExtended.php https://github.com/RetroAchievements/RAWeb/blob/develop/public/API/API_GetGameInfoAndUserProgress.php

**Comment by meleu** [comment]
@luchaos 
Sounds fair.

And regarding Code Notes. After a second thought I decided to create another command for it and will only allow it to be used on devs/jrdevs channels.

Closing this.

**Pull request closed without merging**
