### PR TITLE
Improve interface

### PR DESCRIPTION
**Pull request by Krylan**
It contains a few small changes to improve (mainly apperance in CSS) some main elements of the website, for better readability and semantics. It also fixes problem with long links in the comments section (reported on Discord channel), which can broke the width of it. It's only a part of planned changes I would like to provide on Retro Achievements.

I'm open to discussion and suggestions/tasks for next changes.

### CODE REVIEW

**Comment by kdecks** [comment]
@Krylan I won't comment on the changes as I'm not a webmaster and can't easily see your changes, but I'm glad to see you are interested in helping make Retroachievements.org a better site for the community!

**Comment by meleu** [comment]
the upper menu with no background looks much more cleaner indeed :ok_hand: 

> I'm open to discussion and suggestions/tasks for next changes.

One task I was willing to do is to separate all inline CSS and JS scripts from the PHP files, putting them in `public/css` and `public/js` directories. If you could take care of this it would be very much appreciated.

**Comment by Krylan** [comment]
@kdecks thank you. Such words are really encorauging to do more.

> One task I was willing to do is to separate all inline CSS and JS scripts from the PHP files, putting them in public/css and public/js directories.

@meleu good suggestion, I can take care of it. I have also plan to get rid of _mobile.css file for sake of responsive web design. When elements of the website will be adapted for different screen sizes, separate file will be not needed, as well as detection of mobile visits (at least for this case).
Unfortunately, for some design changes, I would need a database fill/seed, to have better view on how things look like on the website (I have only few records, which I inserted manually into DB).

As it's the first open-source project I'm contributing, I'm new to these pull requests and issues: I will surely make new changes on this branch on my fork. Should I open new pull requests each time I want to commit my work to develop branch with changes?

**Comment by meleu** [comment]
> Should I open new pull requests each time I want to commit my work to develop branch with changes?

Yes. It's also a good practice to have a separate branch for each new feature you're working on.

**Pull request merged**
