### PR TITLE
chore: refactor Site namespace to default namespaces

### PR DESCRIPTION
**Pull request by luchaos**
Refactors `Site` namespaces to Laravel's default namespaces using PHPStorm's refactoring capabilities:
```
\App\Site -> \App
\App\Site\*ServiceProvider -> \App\Providers\
\App\Site\Commands\ -> \App\Console\Commands\
\App\Site\Controllers\ -> \App\Http\Controllers\
\App\Site\Middleware\ -> \App\Http\Middleware\
\App\Site\Requests\ -> \App\Http\Requests\
\App\Site\Responses\ -> \App\Http\Responses\
\App\Support\Http\ -> \App\Http\
\Tests\Feature\Site -> \Tests\Feature\
```
This allows to use `artisan`'s various `make` commands which assume default namespaces.

### CODE REVIEW

**Review by wescopeland — APPROVED** [review]
There is a merge conflict in the branch, but I think strategically it might make sense to merge this sooner rather than later.

**Comment by Jamiras** [comment]
> strategically it might make sense to merge this sooner rather than later.

I think the plan was to merge it as soon as we felt the release was stable. Maybe sometime Saturday?

**Comment by wescopeland** [comment]
> I think the plan was to merge it as soon as we felt the release was stable. Maybe sometime Saturday?

That sounds good to me 👍

**Comment by luchaos** [comment]
yup, waiting at least another day to see if the current changes require adjustments sounds reasonable.
I'll rebase/resolve until then.

**Review by Jamiras — APPROVED** [review]

**Pull request merged**
