### PR TITLE
Create uk_UA.json

### PR DESCRIPTION
**Pull request by QmanaQ**
Translated.

### CODE REVIEW

**Comment by wescopeland** [comment]
There are going to be a lot of conflicts after https://github.com/RetroAchievements/RAWeb/pull/2807 is merged. I recommend holding off until then.

**Comment by QmanaQ** [comment]
> There are going to be a lot of conflicts after #2807 is merged. I recommend holding off until then.

but i translated from file en_US.json

**Comment by taras240** [comment]
I think `Beaten` should be translated as `Пройдено`

**Comment by wescopeland** [comment]
@QmanaQ 
> And you can update new file (if possible)

Sorry, I won't be able to do that.

We're a global community; I'm delighted to include most any locale into RAWeb. It's very important that #2807 is merged first in order to resolve a major issue, otherwise we can't actually turn any of them on.

When you opened discussion #2817, I thought you were asking if l10n support was even being considered for the roadmap. If I had guessed you were planning on opening a PR, I would've mentioned #2807 immediately.

To avoid further confusion, I've made a temporary edit to the translations doc.

Once #2807 is merged, there are going to be a lot of conflicts in this branch. You can see what the new en_US.json file looks like by visiting this link: https://github.com/RetroAchievements/RAWeb/blob/5e5bd339256c67619ef5131a63200b65eeca5c07/lang/en_US.json

**Comment by wescopeland** [comment]
#2807 has been merged. I'm happy to accept the _uk_UA.json_ file after it has been updated accordingly.

**Comment by QmanaQ** [comment]
> There are multiple inconsistencies and some awkward translations, for example:
> * `ROMs` is translated as `ROMs` or `ПЗУ`. Is `ПЗУ` commonly used in Ukrainian? I would suggest `ROMи` and `ROMів`;
> * `Beaten` is translated as `виграно`, `побито`, and `програно`, with the last being especially confusing;
> * `Achievements` is translated as `відзнаки` and `досягнення`. I would suggest `досягнення`, as `відзнаки` is more suitable for `Site`, `Game`, and `Event` `Awards`;
> * Both `Legal & Terms` and `Privacy Policy` are translated as `Політика конфіденційності`;
> * `Захищених авторським правом немає ROMs доступні для завантаження на RetroAchievements.org.` is not legible.
> 
> I’ve focused on the key issues here, but will gladly provide further feedback on other points if needed.

just stop use google translator, you know, he cant translate normaly

**Comment by QmanaQ** [comment]
the request was canceled because I do not understand programming languages in general. i can't change anything, i start from 0

**Comment by wescopeland** [comment]
Hi @QmanaQ!

As mentioned in [this comment](https://github.com/RetroAchievements/RAWeb/pull/2819#issuecomment-2465500627), there are now several inconsistencies in this branch's uk_UA.json when compared to en_US.json.

I would be very happy to accept uk_UA as a locale, but it's impossible for me to do so until it's resynced against en_US 😞

For the time being, I'll set this branch to draft. When the JSON file is ready for review, please feel free to move the PR back out of draft status. Thank you for your understanding!

**Comment by QmanaQ** [comment]
i will use google docs to make changes

**Comment by QmanaQ** [comment]
file deleted. files update sucks because i cant norlmaly fix file

**Comment by wescopeland** [comment]
@fomdt @taras240 If either of you would like to continue this in a separate PR, I would be happy to accept it!

**Pull request closed without merging**
