### PR TITLE
[WiP] add support for RAQUASI88 (NEC PC-8000/8800 emulator) - closes #254

### LINKED ISSUE #254: add PC-8800 as a supported system
just some notes for self (most likely will be done tonight):
- [x] add a RAQUASI88 entry to `src/Emulators.php`
- [x] add a RAQUASI88 entry to `latestclient` in `public/dorequest.php`

After binary is available (waiting for @rzumer / @Jamiras)
- [x] add the PC-8800 console ID as valid in `isValidConsoleID()` (`lib/database/game.php`)
- [x] create a `LatestRAQUASI88Version.html`
- [x] upload the binary
- [x] add an entry in the downloads page

### PR DESCRIPTION
**Pull request by meleu**
# This PR is ready to be merged *as soon as RAIntegration 0.75 is released*.

Got some boring time ~~while at work~~ and decided to do these things in advance.

- added a RAQUASI88 entry to `src/Emulators.php`
- added a RAQUASI88 entry to `latestclient` in `public/dorequest.php`
- added the PC-8800 console ID as valid in `isValidConsoleID()` (`lib/database/game.php`)
- added an entry in the downloads page

~~Waiting the RAQUASI88 binary to finish the next steps:~~
Steps already taken (09/January/2019) outside this PR
- created a `LatestRAQUASI88Version.html`: http://retroachievements.org/LatestRAQUASI88Version.html
- uploaded the `RAQUASI88.zip` binary: retroachievements.org/bin/RAQUASI88.zip

### CODE REVIEW

**Comment by rzumer** [comment]
Existing references to PC-8800 in other pages probably need to be replaced with PC-8000/8800 for consistency.

**Comment by meleu** [comment]
This needs to be done directly on the database, not on the backend's code.

@luchaos / @ScottFromDerby can some of you please rename the console ID 47 from `PC-8800` to `PC-8000/8800`?

Thanks in advance.

**Comment by Jamiras** [comment]
I have the binary file ready (attached). Since it's dependent on the 0.75 dll, we should wait for that to be released before finalizing this PR.
[RAQUASI88.zip](https://github.com/RetroAchievements/RAWeb/files/2738788/RAQUASI88.zip)

**Comment by meleu** [comment]
Steps already taken outside this PR
- created a `LatestRAQUASI88Version.html`: https://retroachievements.org/LatestRAQUASI88Version.html
- uploaded the `RAQUASI88.zip` binary: https://retroachievements.org/bin/RAQUASI88.zip

Which makes this PR ready to be merged ***as soon as RAIntegration 0.75 is released***.

If I am not online when RAIntegration 0.75 is released, you guys can try @luchaos to merge and deploy this PR. :+1:

**Comment by rzumer** [comment]
It seems that a database change is needed to support the new latest version API endpoint. The `LatestXyzVersion.html` pages do not seem to be used by the current version of `RAIntegration`.

**Comment by Jamiras** [comment]
New zip file for v1.1 of RAQUASI88:
[RAQUASI88.1.1.zip](https://github.com/RetroAchievements/RAWeb/files/2798455/RAQUASI88.1.1.zip)

**Comment by meleu** [comment]
Uploaded the binary and changed the `LatestRAQUASI88Version.html` accordingly.

**Pull request merged**
