### PR TITLE
chore(docker)!: replace mailhog with mailpit

### PR DESCRIPTION
**Pull request by luchaos**
The Laravel Sail default setup switched from mailhog to mailpit.

See https://github.com/laravel/sail/pull/533

Make sure to update `.env` with the new variable:

```
FORWARD_MAILPIT_DASHBOARD_PORT=64050
FORWARD_MAILPIT_PORT=64051
...
MAIL_PORT=${FORWARD_MAILPIT_PORT}
```

Rebuild by running `sail up` or `sail up -d` (daemonized). The web interface remains at http://localhost:64050/

### CODE REVIEW

**Comment by wescopeland** [comment]
https://github.com/RetroAchievements/RAWeb/blob/cb68f174f1783eef57a2d844b116ad97f9b9368d/README.md?plain=1#L112

Anything here worth updating?

**Comment by wescopeland** [comment]
Also wondering if this reference should be updated: https://github.com/RetroAchievements/RAWeb/blob/cb68f174f1783eef57a2d844b116ad97f9b9368d/config/mail.php#L39

**Comment by wescopeland** [comment]
When I attempt to send a DM locally to a user who has email notifications enabled, I see this:

Screenshot 2023-07-22 at 3 07 03 PM

Possibly related to the comment for _mail.php_ above?

**Comment by luchaos** [comment]
> When I attempt to send a DM locally to a user who has email notifications enabled, I see this:
> 
> Screenshot 2023-07-22 at 3 07 03 PM
> 
> Possibly related to the comment for _mail.php_ above?

It is related to that 👍 thanks!
I had those changes stashed for some reason...

**Comment by wescopeland** [comment]
Verified functionality, all is working now. The mailhog UI is sleek; one day we'll have to give these emails a glow up.

Screenshot 2023-07-22 at 4 04 25 PM

**Review by wescopeland — APPROVED** [review]

**Pull request merged**
