### PR TITLE
Allow users to explicitly (un-)subscribe forum topics

### PR DESCRIPTION
**Pull request by gdeOo**
Previously, users were always implicitly subscribed to new comments in forum topics they had commented on. The only way out was to disable notifications globally, thus unsubscribing from every forum topic.

Users can now explicitly unsubscribe from specific forum topics they are currently subscribed to. This operation can be used to nullify the implicit subscription that occurs when the user comments on a topic, which is still the default behaviour.

Users are also free to re-subscribe to a previously unsubscribed topic, or even subscribe to topics that they have not commented on.

------

There was no place for operations in the forum topic view, so I added a little area below the forum title. It can be moved somewhere if that's preferable.

image

### CODE REVIEW

**Comment by luchaos** [comment]
Very nice! Thanks for taking care of it @gdeOo .

Going by the changes it looks like the subscriptions only handle forum topic subscriptions. I'd argue that it would be nice if it handled user wall and ticket comments as well.

My suggestions: make it a generalized solution that allows to handle multiple types of resources, not only forum topics, to be reused in other areas as well.

`ForumTopicSubscription` -> `Subscription` 
`ForumTopicID` -> `ModelType` & `ModelID`
`updateForumTopicSubscription` -> `updateSubscription` with type added to the parameters
`isUserSubscribedToForumTopic ` -> `isUserSubscribedTo` with type added to the parameters
etc.

That's how it's implemented in v2 at least (I'll write an importer for said subscriptions). If we agree on not going that far in v1 that's ok as well and i'll just merge this PR with the forum topic subscriptions only.

**Comment by gdeOo** [comment]
I'm ok with generalizing this to handle other notification use cases.

Just to make sure we're on the same page, the use cases you mentioned are the following, right?

1. (Un-)subscribe from the wall of a given user.
2. (Un-)subscribe from tickets of a given game. Should probably be a dev-only thing, right?

I can think of at least three other use cases that would make sense:

4. (Un-)subscribe from the wall of a given game.
5. (Un-)subscribe from user comments on achievements of a given game. Probably a dev-only thing as well.
6. (Un-)subscribe from user comments on a given achievement. Similar to 2, but for normal users that may not want to be notified of future comments on an achievement that they have commented on.

What do you think?

**Comment by meleu** [comment]
Once this PR is merged, it closes issue #5.

**Comment by luchaos** [comment]
@gdeOo yes, covering all those use cases would be perfect!

**Comment by gdeOo** [comment]
Updated with the additional functionality.

Besides forum topics, users can now subscribe to or unsubscribe from:
  * Comments on a specific user wall
  * Comments on a specific game wall
  * Comments on a specific achievement

In addition, developers can now subscribe to or unsubscribe from:
  * Comments on any achievement of a specific game
  * Tickets reported for any achievement of a specific game, regardless of authorship

----

Also, fair warning: The code that sent the emails for non-forum activity was a bit of a mess of copy paste with a bunch of special cases, making it difficult to introduce the new functionality. As such, I had to substantially refactor that part of the code. I tried hard to leave everything working as was, but I'd say the probability of having gotten _everything_ right on first try without automated tests is not the best...

**Comment by Keltron3030** [comment]
Nice work

**Comment by luchaos** [comment]
Fantastic @gdeOo ! I'll merge in the changes, do some tests, and have it deployed asap.

**Pull request merged**
