### PR TITLE
Fix asterisk placement on long game titles in user claims list

### PR DESCRIPTION
**Pull request by anegoda1995**
Fixes issue https://github.com/RetroAchievements/RAWeb/issues/1430

### CODE REVIEW

**Comment by wescopeland** [comment]
I still seem to be able to repro this issue on mobile:

Screenshot 2023-12-10 at 8 32 09 AM

Notice the "*" underneath Detective Conan & Kindaichi Case Files: Chance Encounter of 2
Great Detectives (Nintendo DS). It should instead read:

> Detective Conan & Kindaichi Case Files: Chance Encounter of 2 Great Detectives (Nintendo DS)*

without a line break.

**Comment by anegoda1995** [comment]
I tested on all 3 mobile width
image
image
image

@wescopeland can you confirm that:
1. the asteriks move on new line;
2. tag <a> has class **inline-block**?

**Comment by wescopeland** [comment]
Sorry, there was something wrong on my end when pulling down the branch for this PR.

I'm seeing the correct behavior now:

Screenshot 2023-12-10 at 8 58 16 PM

There is a slight behavior change. A space seems to have been added between the game title and the "*" character:

Screenshot 2023-12-10 at 8 59 09 PM

**Comment by wescopeland** [comment]
This issue has been resolved in #2175. The target component this PR addresses has been rewritten, and no longer exists in its current form.

**Pull request closed without merging**
