### PR TITLE
Add Server comment when updating leaderboard or removing player entries

### PR DESCRIPTION
**Pull request by Tsearo**
Small update to add System comments on a leaderboard pages comments section whenever a developer hits the update button for a leaderboard as well as when an entry is removed. Currently there is nothing stopping developers from doing these things as they please so this should help add some deterrent to that as well as give people peace of mind that nobody has changed their logic if things are acting weird.

Example of the messages:
image

Edit* Added another message for deleting all entries which I forgot. Could also add a message for leaderboard creation but I didn't see the need since they will be updated immediately after created. It could be useful for tracking when the leaderboard was created though

### CODE REVIEW

**Comment by televandalist** [comment]
Merge wen

**Comment by meleu** [comment]
@Tsearo needs to merge some recent changes in order to make this PR mergeable.

image

**Comment by HolyShinx** [comment]
That looks really good. I would also wish from a user perspective for leaderboard tickets, I don't know if it's really possible though

**Comment by Tsearo** [comment]
I pushed a button on here and it said it merged master into by branch, I hope this did what was needed :ssweat:

**Review by meleu — APPROVED** [review]

**Pull request merged**
