### PR TITLE
Report broken achievements from site.

### PR DESCRIPTION
**Pull request by GameDragon2k**
Closes issue https://github.com/RetroAchievements/RAWeb/issues/95

Adds a link to each achievement page that allows **registered** users to submit tickets.
The checksum field is currently optional. It also does not have any kind of md5 validation, which should probably be added.

My php is extremely rusty. It would be nice if someone looked over this and cleaned it up.
@ScottFromDerby  @luchaos  @meleu

### CODE REVIEW

**Comment by meleu** [comment]
I'm also a PHP n00b and currently unable to test, but it's a nice addition!

> The checksum field is currently optional. It also does not have any kind of md5 validation, which should probably be added.

I don't know how to use Regular Expressions in PHP, but if we find out how to do it, here is the expression I use to validate MD5s on my bash scripts: `^[AFa-f0-9-]{32}`.

**Comment by meleu** [comment]
Regarding MD5, I had another idea: how about letting the user choose from a list of linked ones?

If the user is using a ROM with a checksum different from the listed ones, then they shouldn't open a ticket.

**Comment by meleu** [comment]
How **I think** we can get the list of linked hashes:

https://github.com/RetroAchievements/RAWeb/blob/master/public/attemptunlink.php#L28L35

and then show it:

https://github.com/RetroAchievements/RAWeb/blob/master/public/attemptunlink.php#L77L80

**Comment by GameDragon2k** [comment]
While that's not a bad idea, the reason I made the field optional is because most normal users don't know what their MD5 is, how to find it, or even what it's purpose is. This is especially true for RetroArch users.

I don't know if having a list of MD5s would help this. If anything, I could see some users viewing it as just gibberish numbers and letters, and causing them more confusion.

**Comment by meleu** [comment]
@GameDragon2k We can leave it as optional, not mandatory.

**Comment by luchaos** [comment]
i'd leave optional as well until there are easier ways to reason about the hash in question, like report achievements links in emulators could include the hash in the link and prefill that field

**Comment by GameDragon2k** [comment]
@meleu Thinking about it more, it's probably better for the user to input it manually than through a list, especially in the cases of games that have large amounts of verified checksums.

**Comment by GameDragon2k** [comment]
@luchaos The emulators already automatically submit their hashes.

**Comment by meleu** [comment]
@GameDragon2k I was thinking on something like this:

dropdown

But I'm OK on leaving it as a text field to input it manually for now. We can work on better ways to define the checksum later ;)

**Comment by kdecks** [comment]
Great news! Well done @GameDragon2k 
If I recall correctly the CRC32 is the only hash visible from Retroarch. Perhaps that field can take this fact (if it's true) into consideration.

**Pull request merged**
