### PR TITLE
Update release.php

### PR DESCRIPTION
**Pull request by televandalist**
Adds 74 - Arcadia 2001, 75 - Interton VC 4000, and 76 - Elektor TV Games Computer to console list.

### CODE REVIEW

**Comment by televandalist** [comment]
Also, whenever the PC Engine/PC Engine CD split actually happens, the following entries will need to be changed to console ID 76:
```
4706    Legend of Xanadu (CD)
4855    Akumajou Dracula X: Chi no Rondo (CD)
5207    Mad Stalker - Full Metal Force (CD)
5243    Horror Story (CD)
6204    Godzilla | Goijira: Bakutou Retsuden (CD)
6373    Jim Power in Mutant Planet (CD)
6700    Ys: Book I & II (CD)
7098    Advanced Variable Geo (CD)
7903    Shin Megami Tensei (CD)
7961    Splash Lake (CD)
7962    Brandish (CD)
8213    Strider Hiryuu (CD)
8560    Steam Heart's (CD)
8717    Legend of Xanadu 2 (CD)
8838    Ys III: Wanderers from Ys (CD)
8839    Ys IV: The Dawn of Ys (CD)
8841    L-DIS (CD)
8851    Manhole, The (CD)
8864    R-Type Complete (CD)
8865    Gradius II: Gofer no Yabou (CD)
8866    Gate of Thunder (CD)
8867    Lords of Thunder (CD)
8868    Ginga Fukei Densetsu Sapphire (CD)
8877    It Came from the Desert (CD)
8994    Sorcerian (CD)
9021    Prince of Persia (CD)
9165    Fighting Street (CD)
9166    Forgotten Worlds (CD)
9174    Cotton: Fantastic Night Dreams (CD)
9531    Loom (CD)
9709    Chou Jikuu Yousai Macross 2036 (CD)
9871    Summer Carnival 93 - Nexzr Special (CD)
9874    Shapeshifter (CD)
9882    Popful Mail (CD)
10197   Dragon Slayer - The Legend of Heroes II (CD)
12782   Beyond Shadowgate (CD)
12836   Baby Jo: The Super Hero (CD)
12841   Shadow of the Beast (CD)
12886   Exile (CD)
12887   Exile - Wicked Phenomenon (CD)
12888   Vasteel (CD)
12889   Dragon Slayer - The Legend of Heroes (CD)
12890   Cosmic Fantasy 2 (CD)
12891   Dungeon Explorer II (CD)
12892   Valis II (CD)
12893   Valis III (CD)
13133   Faussete Amour (CD)
13134   Sylphia (CD)
13166   Dead of the Brain 1 and 2 (CD)
13184   Buster Bros. (CD)
13185   Puyo Puyo CD (CD)
13186   Puyo Puyo CD Tsuu (CD)
13187   Shanghai II (CD)
13188   Motteke Tamago (CD)
13189   Download 2 (CD)
13190   Addams Family (CD)
13191   Space Invaders - The Original Game (CD)
13192   Zero Wing (CD)
13193   Tengai Makyou: Fuun Kabuki Den (CD)
13194   ~Unlicensed~ Implode (CD)
13195   Gain Ground SX (CD)
13196   Golden Axe (CD)
13197   Rainbow Islands (CD)
13306   Monster Lair (CD)
13307   Death Bringer - The Knight of Darkness (CD)
13308   Bomberman Panic Bomber (CD)
13309   Shanghai III: Dragon's Eye (CD)
13310   Super Darius (CD)
13311   Super Darius II (CD)
13414   GÃ¶tzendiener (CD)
13415   Xak III - The Eternal Recurrence (CD)
13615   Ginga Ojousama Densetsu Yuna (CD)
13646   Kaizou Choujin Shubibinman 3: Ikai no Princess (CD)
13647   Kaze Kiri - Ninja Action (CD)
14027   Super Air Zonk - Rockabilly-Paradise (CD)
14028   Star Parodier (CD)
14089   John Madden Duo CD Football (CD)
14090   Dungeon Master - Therons Quest (CD)
14091   J.B. Harold - Murder Club (CD)
14092   Jack Nicklaus - Turbo Golf (CD)
14093   Last Alert (CD)
14094   Lords of the Rising Sun (CD)
14095   Magical Dinosaur Tour (CD)
14096   Might and Magic III: Isles of Terra (CD)
14097   Riot Zone (CD)
14098   Sherlock Holmes - Consulting Detective (CD)
14099   Sherlock Holmes - Consulting Detective Vol. 2 (CD)
14100   SimEarth - The Living Planet (CD)
14101   Syd Meads Terraforming (CD)
14102   Bonk 3: Bonks Big Adventure (CD)
14103   Camp California (CD)
14104   Final Zone II (CD)
14139   Gyuwambler Jiko Chushinha (CD)
14143   Gyuwambler Jiko Chushinha: Mahjong Puzzle Collection (CD)
14247   Fiend Hunter (CD)
14465   Kiaidan 00 (CD)
14480   Mugen Senshi Valis - The Legend of a Fantasm Soldier (CD)
14636   Cho Aniki (CD)
14637   Seirei Senshi Spriggan (CD)
14638   ~Unlicensed~ Hypernova Blast (CD)
14640   Snatcher (CD)
14641   Tokimeki Memorial (CD)
14642   Far East of Eden - Tengai Makyou II - Manji Maru (CD)
14933   Wrestling Universe: Fire Pro Joshi - Doumu Chou Taisen - Zenjo vs. JWP (CD)
15442   Bishoujo Senshi Sailor Moon Collection (CD)
15486   Yu Yu Hakusho (CD)
15587   Nekketsu Koukou Dodge Ball-Bu: CD Soccer-hen (CD)
15588   Downtown Nekketsu Koushinkyoku: Soreyuke Daiundoukai (CD)
15589   Downtown Nekketsu Monogatari (CD)
15590   Double Dragon II: The Revenge (CD)
16302   Fray CD: Xak Gaiden (CD)
16304   Dragon Ball Z: Idainaru Son Goku Densetsu (CD)
16978   Ai Chou Aniki (CD)
16979   Chiki Chiki Boys (CD)
16980   Chou Jikuu Yousai Macross - Eien no Love Song (CD)
16981   Hyper Dyne SideArms Special (CD)
16982   ImageFight II - Operation Deepstriker (CD)
16983   Spriggan Mark 2 - Re Terraform Project (CD)
16984   Startling Odyssey (CD)
16985   Startling Odyssey II - Maryuu Sensou (CD)
16986   Summer Carnival '92 - Alzadick (CD)
16987   Valis IV (CD)
17039   ~Unlicensed~ FX Unit Yuki - The Henshin Engine (CD)
17137   Bazaru de Gozaru no Game de Gozaru (CD)
18279   Bishoujo Senshi Sailor Moon (CD)
18737   Rayxanber II (CD)
19925   F1 Circus Special: Pole to Win (CD)
20226   Madou Monogatari I: Honoo no Sotsuenji (CD)
```

**Review by Jamiras — APPROVED** [review]

**Comment by luchaos** [comment]
Can this be merged anytime or do the [changes in the toolkit](https://github.com/RetroAchievements/rcheevos/pull/204) have to be in place first?

**Comment by Jamiras** [comment]
I think this will need to wait until the corresponding changes are deployed in RAlibretro, or users trying to load PC-Engine CD games through RAlibretro will get an error indicating the server console ID doesn't match the client console ID (see https://github.com/RetroAchievements/RAIntegration/pull/820).

RetroArch (until it is updated, and older versions once it is) will use the SYSTEM_RAM followed by SAVE_RAM paradigm as there won't be a memory map defined. This will likely cause incompatibilities for any achievement using the CD-expanded RAM (which I expect to be most of them). A quick test of Beetle PCE Fast (possibly updated since my copy) shows that it only exposes the basic 8K of SYSTEM_RAM correctly, and what I'm assuming is the "CD Battery-backed RAM" as 2K of SAVE_RAM. The "CD RAM" and "Super System Card RAM" are missing. Since the SAVE_RAM is so much smaller than the missing RAM, I would expect most achievements depending on the extra RAM to be marked as Unsupported.

**Comment by Jamiras** [comment]
This PR should also remove the ETA message in lib/render/content.php

**Pull request merged**
